services:
  # 1) MySQL
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  # 2) WordPress
  wordpress:
    image: wordpress:6.5-php8.2-apache
    depends_on:
      - db
    restart: always
    ports:
      - "8000:80"
    env_file:
      - .env
    environment:
      # Ces variables sont lues par l’image officielle WP
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      JWT_AUTH_SECRET_KEY: ${JWT_AUTH_SECRET_KEY}
      CORS_ALLOWED_ORIGIN: ${CORS_ALLOWED_ORIGIN}
    volumes:
      # Monte ton dossier wp-content local dans le conteneur
      - ./wp-content:/var/www/html/wp-content

  # 3) phpMyAdmin (optionnel)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    platform: linux/amd64 # nécessaire sur Mac M1/M2
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
  db_data:
  wp_content_data:
